---
title: "Proyecto Valoración"
author: "Monica"
date: "2023-12-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

     
     
     
```{r}
library(forecast)
###Para silver futuro  ST_silver_futuro
adf_test <- adf.test(ST_copper_futuro)
print(adf_test)
# Define the range for p, d, q
p <- 0:10
d <- 0
q <- 0:10

# Create a data frame with all combinations of p, d, q
pdq <- expand.grid(p = p, d = d, q = q)

# Apply the ARIMA model to each combination
results <- apply(pdq, 1, function(x) {
  tryCatch({
    model <- arima(ST_copper_futuro, order = c(x['p'], x['d'], x['q']))
    return(c(x, AIC = AIC(model)))
  }, error = function(e) {
    return(NULL)
  })
})

###Para silver futuro  ST_silver_spot
adf_test <- adf.test(ST_copper_spot)
print(adf_test)
# Define the range for p, d, q
p <- 0:10
d <- 0:10
q <- 0:10

# Create a data frame with all combinations of p, d, q
pdq <- expand.grid(p = p, d = d, q = q)

# Apply the ARIMA model to each combination
results <- apply(pdq, 1, function(x) {
  tryCatch({
    model <- arima(ST_copper_spot, order = c(x['p'], x['d'], x['q']))
    return(c(x, AIC = AIC(model)))
  }, error = function(e) {
    return(NULL)
  })
})
```
     
     
     
```{r}
ST_copper_futuro <- ts(copper$Future, frequency = 12)
ms_copper_futuro <- auto.arima(ST_copper_futuro)

ST_copper_spot<-ts(copper$Spot,frequency=12)

ms_copper_spot<-arima(ST_copper_spot,c(0,0,6))
ms_copper_spot <- arima(ST_copper_spot,c(1,0,10))



proyecciones_futuro_copper<- forecast(ms_copper_futuro, h = meses_proyectar)
proyecciones_spot_copper<- forecast(ms_copper_spot, h = meses_proyectar)

plot(proyecciones_futuro_copper)
plot(proyecciones_spot_copper)

copper_proyecciones<-data_frame(Date=as.Date(fechas_formato),
                                Future=proyecciones_futuro_copper$mean,
                                Spot=proyecciones_spot_copper$mean )
copper_completo<-bind_rows(copper,copper_proyecciones)


```
  
```{r}
copper_completo$Date <- as.Date(paste0(copper_completo$Date, "-01"), format = "%Y-%m-%d")
copper_completo$periodoF <- ifelse(copper_completo$Date > as.Date("2023-10-01"), "DespuésF", "AntesF")
copper_completo$periodoS <- ifelse(copper_completo$Date > as.Date("2023-10-01"), "DespuésS", "AntesS")

ggplot(data = copper_completo) + 
  geom_line(aes(x = Date, y = Future, group = 1, color = periodoF)) +
  #geom_line(aes(x = Date, y = Spot, group = 1, color = periodoS)) +
  scale_color_manual(values = c("AntesF" = "black", "DespuésF" = "blue", "AntesS" = "red", "DespuésS" = "purple"))

```
     
```{r}
library(forecast)
###Para silver futuro  ST_silver_futuro
adf_test <- adf.test(ST_silver_futuro)
print(adf_test)
# Define the range for p, d, q
p <- 0:10
d <- 0
q <- 0:10

# Create a data frame with all combinations of p, d, q
pdq <- expand.grid(p = p, d = d, q = q)

# Apply the ARIMA model to each combination
results <- apply(pdq, 1, function(x) {
  tryCatch({
    model <- arima(ST_silver_futuro, order = c(x['p'], x['d'], x['q']))
    return(c(x, AIC = AIC(model)))
  }, error = function(e) {
    return(NULL)
  })
})

###Para silver futuro  ST_silver_spot
adf_test <- adf.test(ST_silver_spot)
print(adf_test)
# Define the range for p, d, q
p <- 0:10
d <- 0
q <- 0:10

# Create a data frame with all combinations of p, d, q
pdq <- expand.grid(p = p, d = d, q = q)

# Apply the ARIMA model to each combination
results <- apply(pdq, 1, function(x) {
  tryCatch({
    model <- arima(ST_silver_spot, order = c(x['p'], x['d'], x['q']))
    return(c(x, AIC = AIC(model)))
  }, error = function(e) {
    return(NULL)
  })
})




```
     
```{r}
##Creo que ideal 10,0,9
ST_silver_futuro <- ts(silver$Future, frequency = 12)
#Ideal 10,0,9
ST_silver_spot<-ts(silver$Spot,frequency=12)

ms_silver_futuro<-arima(ST_silver_futuro,order=c(10,0,9))
ms_silver_spot <- arima(ST_silver_spot,order=c(10,0,9))


proyecciones_futuro_silver<- forecast(ms_silver_futuro, h = meses_proyectar)
proyecciones_spot_silver<- forecast(ms_silver_spot, h = meses_proyectar)


plot(proyecciones_futuro_silver)
plot(proyecciones_spot_silver)



silver_proyecciones<-data_frame(Date=fechas_formato,
                              Future=proyecciones_futuro_silver$mean,
                              Spot=proyecciones_spot_silver$mean )
silver_completo<-bind_rows(silver,silver_proyecciones)
```

```{r}
silver_completo$Date <- as.Date(paste0(silver_completo$Date, "-01"), format = "%Y-%m-%d")
silver_completo$periodoF <- ifelse(silver_completo$Date > as.Date("2023-10-01"), "DespuésF", "AntesF")
silver_completo$periodoS <- ifelse(silver_completo$Date > as.Date("2023-10-01"), "DespuésS", "AntesS")

ggplot(data = silver_completo) + 
  geom_line(aes(x = Date, y = Future, group = 1, color = periodoF)) +
  #geom_line(aes(x = Date, y = Spot, group = 1, color = periodoS)) +
  scale_color_manual(values = c("AntesF" = "black", "DespuésF" = "blue", "AntesS" = "red", "DespuésS" = "purple"))

```
```{r}
  goldP<-head(gold,155-12)
  ST_goldP_futuro <- ts(goldP$Future, frequency = 12)
  ST_goldP_spot<-ts(goldP$Spot,frequency=12)
```

```{r}
  adf_test <- adf.test(ST_goldP_futuro)
  print(adf_test)
# Define the range for p, d, q
p <- 0:10
d <- 0
q <- 0:10

# Create a data frame with all combinations of p, d, q
pdq <- expand.grid(p = p, d = d, q = q)

# Apply the ARIMA model to each combination
results1 <- apply(pdq, 1, function(x) {
  tryCatch({
    model <- arima(ST_goldP_spot, order = c(x['p'], x['d'], x['q']))
    return(c(x, AIC = AIC(model)))
  }, error = function(e) {
    return(NULL)
  })
})
#  
results <- apply(pdq, 1, function(x) {
  tryCatch({
    model <- arima(ST_goldP_futuro, order = c(x['p'], x['d'], x['q']))
    return(c(x, AIC = AIC(model)))
  }, error = function(e) {
    return(NULL)
  })
})#5,1,2
```

```{r}
ms_goldP_futuro<-arima(ST_goldP_futuro,order=c(2,0,0))
ms_goldP_spot <- arima(ST_goldP_spot,order=c(0,0,2))


proyecciones_futuro_goldP<- forecast(ms_goldP_futuro, h = 12)
proyecciones_spot_goldP<- forecast(ms_goldP_spot, h = 12)


plot(proyecciones_futuro_goldP)
plot(proyecciones_spot_goldP)


#print(silver$Date)
#print(fechas_formato)
fechas <- seq(from = ym("2022-11"), by = "months", length.out = 12)
fechas_formatoP <- as.Date(format(fechas, "%Y-%m-%d"))

goldP_proyecciones<-data_frame(Date=as.Date(fechas_formatoP),
                              Future=proyecciones_futuro_goldP$mean,
                              Spot=proyecciones_spot_goldP$mean )
goldP_completoP<-bind_rows(goldP,goldP_proyecciones)
```

     
     